# Use the official Node.js 23.3.0 image from the Docker Hub
FROM node:23.3.0

# Create and change to the app directory
WORKDIR /app

# Copy application dependency manifests to the container image
COPY package*.json ./

# Install production dependencies
RUN npm install

# Copy local code to the container image
COPY . .

# Expose the port the app runs on
EXPOSE 5173

# Run the web service on container startup
CMD [ "npm", "run", "docker" ]